module.exports = [
  // Biryani
  {
    categorySlug: 'biryani',
    name: 'Chicken Biryani',
    slug: 'chicken-biryani',
    description: 'Aromatic basmati rice cooked with tender chicken and traditional spices.',
    price: 299,
    discountPrice: 249,
    image: '/assets/products/chicken-biryani.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.7,
    totalReviews: 128,
    stock: 50
  },
  {
    categorySlug: 'biryani',
    name: 'Mutton Biryani',
    slug: 'mutton-biryani',
    description: 'Rich and flavorful mutton biryani prepared with aromatic spices.',
    price: 399,
    discountPrice: 349,
    image: '/assets/products/mutton-biryani.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'high',
    preparationTime: 35,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    totalReviews: 96,
    stock: 42
  },
  {
    categorySlug: 'biryani',
    name: 'Veg Biryani',
    slug: 'veg-biryani',
    description: 'Fragrant basmati rice with fresh vegetables and aromatic spices.',
    price: 229,
    discountPrice: 199,
    image: '/assets/products/veg-biryani.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 20,
    isAvailable: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.4,
    totalReviews: 74,
    stock: 30
  },

  // North Indian
  {
    categorySlug: 'north-indian',
    name: 'Butter Chicken',
    slug: 'butter-chicken',
    description: 'Creamy tomato-based chicken curry with aromatic Indian spices.',
    price: 329,
    discountPrice: 289,
    image: '/assets/products/butter-chicken.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: false,
    spiceLevel: 'mild',
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    totalReviews: 156
  },
  {
    categorySlug: 'north-indian',
    name: 'Paneer Butter Masala',
    slug: 'paneer-butter-masala',
    description: 'Soft paneer cooked in a creamy tomato gravy.',
    price: 279,
    discountPrice: 239,
    image: '/assets/products/paneer-butter-masala.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'mild',
    preparationTime: 20,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.6,
    totalReviews: 112,
    stock: 50
  },
  {
    categorySlug: 'north-indian',
    name: 'Dal Makhani',
    slug: 'dal-makhani',
    description: 'Slow-cooked black lentils with butter and cream.',
    price: 199,
    discountPrice: 169,
    image: '/assets/products/dal-makhani.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'mild',
    preparationTime: 20,
    isAvailable: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.5,
    totalReviews: 63,
    stock: 50
  },

  // Chinese
  {
    categorySlug: 'chinese',
    name: 'Veg Hakka Noodles',
    slug: 'veg-hakka-noodles',
    description: 'Stir-fried noodles with fresh vegetables and Chinese sauces.',
    price: 189,
    discountPrice: 159,
    image: '/assets/products/veg-hakka-noodles.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 15,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.4,
    stock: 50,
    totalReviews: 89
  },
  {
    categorySlug: 'chinese',
    name: 'Chicken Hakka Noodles',
    slug: 'chicken-hakka-noodles',
    description: 'Stir-fried noodles with chicken and vegetables.',
    price: 229,
    discountPrice: 199,
    image: '/assets/products/chicken-hakka-noodles.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 15,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.6,
    stock: 50,
    totalReviews: 104
  },
  {
    categorySlug: 'chinese',
    name: 'Veg Fried Rice',
    slug: 'veg-fried-rice',
    description: 'Classic fried rice with fresh vegetables.',
    price: 179,
    discountPrice: 149,
    image: '/assets/products/veg-fried-rice.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'mild',
    preparationTime: 15,
    isAvailable: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.3,
    stock: 50,
    totalReviews: 51
  },

  // Starters
  {
    categorySlug: 'starters',
    name: 'Chicken Tikka',
    slug: 'chicken-tikka',
    description: 'Juicy chicken pieces marinated in spices and grilled.',
    price: 299,
    discountPrice: 259,
    image: '/assets/products/chicken-tikka.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    stock: 50,
    totalReviews: 141
  },
  {
    categorySlug: 'starters',
    name: 'Paneer Tikka',
    slug: 'paneer-tikka',
    description: 'Grilled paneer cubes marinated with Indian spices.',
    price: 259,
    discountPrice: 219,
    image: '/assets/products/paneer-tikka.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 20,
    isAvailable: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.6,
    stock: 50,
    totalReviews: 88
  },
  {
    categorySlug: 'starters',
    name: 'Chicken Wings',
    slug: 'chicken-wings',
    description: 'Crispy chicken wings tossed in spicy sauce.',
    price: 279,
    discountPrice: 239,
    image: '/assets/products/chicken-wings.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'high',
    preparationTime: 20,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.5,
    stock: 50,
    totalReviews: 72
  },

  // Rolls
  {
    categorySlug: 'rolls',
    name: 'Chicken Roll',
    slug: 'chicken-roll',
    description: 'Soft flatbread filled with spicy chicken and fresh vegetables.',
    price: 159,
    discountPrice: 129,
    image: '/assets/products/chicken-roll.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 12,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.5,
    stock: 50,
    totalReviews: 94
  },
  {
    categorySlug: 'rolls',
    name: 'Paneer Roll',
    slug: 'paneer-roll',
    description: 'Paneer and vegetables wrapped in a soft flatbread.',
    price: 139,
    discountPrice: 119,
    image: '/assets/products/paneer-roll.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: true,
    spiceLevel: 'mild',
    preparationTime: 12,
    isAvailable: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.3,
    stock: 50,
    totalReviews: 61
  },
  {
    categorySlug: 'rolls',
    name: 'Egg Roll',
    slug: 'egg-roll',
    description: 'Egg-filled roll with onions, sauces and spices.',
    price: 129,
    discountPrice: 109,
    image: '/assets/products/egg-roll.jpg',
    images: [],
    foodType: 'egg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 10,
    isAvailable: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.2,
    stock: 50,
    totalReviews: 45
  },

  // Beverages
  {
    categorySlug: 'beverages',
    name: 'Fresh Lime Soda',
    slug: 'fresh-lime-soda',
    description: 'Refreshing lime soda served chilled.',
    price: 79,
    discountPrice: 59,
    image: '/assets/products/fresh-lime-soda.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 5,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.4,
    stock: 50,
    totalReviews: 57
  },
  {
    categorySlug: 'beverages',
    name: 'Mango Shake',
    slug: 'mango-shake',
    description: 'Creamy mango milkshake made with fresh mangoes.',
    price: 129,
    discountPrice: 99,
    image: '/assets/products/mango-shake.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 7,
    isAvailable: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.6,
    stock: 50,
    totalReviews: 83
  },
  {
    categorySlug: 'beverages',
    name: 'Cold Coffee',
    slug: 'cold-coffee',
    description: 'Chilled creamy coffee topped with foam.',
    price: 139,
    discountPrice: 109,
    image: '/assets/products/cold-coffee.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 7,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.5,
    stock: 50,
    totalReviews: 78
  },

  // Desserts
  {
    categorySlug: 'desserts',
    name: 'Gulab Jamun',
    slug: 'gulab-jamun',
    description: 'Soft milk-solid dumplings soaked in sugar syrup.',
    price: 99,
    discountPrice: 79,
    image: '/assets/products/gulab-jamun.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 5,
    isAvailable: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.7,
    stock: 50,
    totalReviews: 119
  },
  {
    categorySlug: 'desserts',
    name: 'Brownie',
    slug: 'brownie',
    description: 'Rich and soft chocolate brownie.',
    price: 129,
    discountPrice: 99,
    image: '/assets/products/brownie.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 5,
    isAvailable: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.5,
    stock: 50,
    totalReviews: 65
  },
  {
    categorySlug: 'desserts',
    name: 'Ice Cream',
    slug: 'ice-cream',
    description: 'Creamy vanilla ice cream.',
    price: 89,
    discountPrice: 69,
    image: '/assets/products/ice-cream.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'none',
    preparationTime: 2,
    isAvailable: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.3,
    stock: 50,
    totalReviews: 42
  },

  // Combos
  {
    categorySlug: 'combos',
    name: 'Chicken Biryani Combo',
    slug: 'chicken-biryani-combo',
    description: 'Chicken biryani served with raita and a beverage.',
    price: 379,
    discountPrice: 319,
    image: '/assets/products/chicken-biryani-combo.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    stock: 50,
    totalReviews: 137
  },
  {
    categorySlug: 'combos',
    name: 'Paneer Meal Combo',
    slug: 'paneer-meal-combo',
    description: 'Paneer curry, dal, rice, roti and beverage.',
    price: 349,
    discountPrice: 299,
    image: '/assets/products/paneer-meal-combo.jpg',
    images: [],
    foodType: 'veg',
    isSpicy: false,
    spiceLevel: 'mild',
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.6,
    stock: 50,
    totalReviews: 76
  },
  {
    categorySlug: 'combos',
    name: 'Family Dinner Combo',
    slug: 'family-dinner-combo',
    description: 'A complete family meal with biryani, starters, curry and drinks.',
    price: 899,
    discountPrice: 749,
    image: '/assets/products/family-dinner-combo.jpg',
    images: [],
    foodType: 'non-veg',
    isSpicy: true,
    spiceLevel: 'medium',
    preparationTime: 35,
    isAvailable: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    stock: 50,
    totalReviews: 201
  }
];